apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eiqj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-eiqj@sha256:7ad0e04a2850d4d878bba2acdee8621d183d39d63cc1851efbf80fa3089c4a77
        name: my-nodejs
        resources: {}
status: {}
